# Generated by Django 3.2 on 2021-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, unique=True)),
                ('pwd_hash', models.CharField(max_length=1000)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('translated_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('picture_url', models.URLField(unique=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='research.Account')),
                ('product_categories', models.ManyToManyField(blank=True, related_name='product_categories', to='research.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('product_availability', models.ManyToManyField(blank=True, related_name='store_availability', to='research.Product')),
            ],
        ),
    ]
