# Generated by Django 3.2 on 2021-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
