# Generated by Django 3.2 on 2021-05-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='kcals',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars',
            field=models.FloatField(blank=True, default=-1),
        ),
    ]
